### ISSUE TITLE
Exactly what I needed!

### ISSUE THREAD

**Issue by EricJorem** [Ev2geny/IngBank2Excel#3]
This is probably not the correct way to send feedback, but I will not pass on the opportunity to thank you wholeheartedly for this tool. I have been squandering so much time to get this data imported into Excel via Power Query and other tools, but I couldn't get it done. I'm only slightly advanced as a user and have already passed the age to muster the enthousiasm to learn coding by myself. So, once again, thanks so much; very much appreciated!

**Comment by Ev2geny** [comment]
@EricJorem , you are welcome. I am glad my app has helped you.

**Comment by Ev2geny** [comment]
> This is probably not the correct way to send feedback,

I just noticed, that indeed the [discussions ](https://github.com/Ev2geny/IngBank2Excel/discussions) section was not enabled. I have now enabled it for general discussions
